### ISSUE TITLE
无法设置订阅

### ISSUE THREAD

**Issue by SORAPSYGA** [s1xu/tg-rss-bot#1]
![image](https://github.com/user-attachments/assets/f60828a2-6231-4163-81e1-11a0d34cf9b2)

如图，已经把bot设置成该频道管理员，但是依旧是这样

**Comment by s1xu** [comment]
试试使用/sub 频道连接。
例如 频道地址是：https://t.me/abcd
使用：/sub  @abcd rssurl

**Comment by SORAPSYGA** [comment]
> 试试使用/sub 频道连接。 例如 频道地址是：https://t.me/abcd 使用：/sub @abcd rssurl

刚才测试了也还是不行，一样提示要我把bot添加到频道
